add awscli option to creds subcommand
YashdalfTheGray/federator pull request #131
Opened 2022-10-31 01:44 UTC by petderek

this allows us to use federator as a credential_process within the context of an aws shared credentials file

2022-10-31 16:17 UTC, YashdalfTheGray requested changes
Can you also add a couple of lines [here](https://github.com/YashdalfTheGray/federator/blob/main/.github/workflows/functional_tests.yml#L37-L50) so that the CI can exercise the new flags on each build?

2022-10-31 16:18 UTC, YashdalfTheGray commented
Also, this closes #130

2022-10-31 19:27 UTC, petderek commented
done. i skipped out on the profile thing because we arent setting a config file anyhwere -- i can try to tease that out if you want but i biased toward 'neh'

2022-11-01 21:08 UTC, merged

2022-11-01 21:09 UTC, YashdalfTheGray commented
Going to cut a release either tonight or tomorrow once the actions have built the binaries! 🙌